import { Suspense } from 'react';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import MobileBottomCta from '@/components/MobileBottomCta';
import ScrollToTop from '@/components/ScrollToTop';
import { AuthProvider } from '@/components/providers/AuthProvider';
import { CarSelectionProvider } from '@/components/providers/CarSelectionProvider';
import { FavoritesProvider } from '@/components/providers/FavoritesProvider';
import { CompareProvider } from '@/components/providers/CompareProvider';
import { SavedBuildsProvider } from '@/components/providers/SavedBuildsProvider';
import SelectedCarBanner from '@/components/SelectedCarBanner';
import SelectedCarFloatingWidget from '@/components/SelectedCarFloatingWidget';

const siteUrl = 'https://supernaturalmotorsports.com';

export const metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'SuperNatural Motorsports | Sports Car Selector & Performance Experts',
    template: '%s | SuperNatural Motorsports',
  },
  description: 'Unleash your racing spirit. Find your perfect sports car with our intelligent selector, plan performance builds with purpose, and join a community that values mastery over materialism. From Miatas to GT3s—we lift up every driver.',
  keywords: [
    'sports cars',
    'track cars', 
    'performance upgrades',
    'motorsports',
    'car selector',
    'sports car comparison',
    'Porsche 911',
    'Porsche Cayman',
    'BMW M3',
    'BMW M4',
    'Corvette C7',
    'Corvette C8',
    'GT cars',
    'track day car',
    'weekend car',
    'sports car buying guide',
    'performance tuning',
    'suspension upgrades',
    'brake upgrades',
    'muscle cars',
    'import tuners',
    'drift cars'
  ],
  authors: [{ name: 'SuperNatural Motorsports' }],
  creator: 'SuperNatural Motorsports',
  publisher: 'SuperNatural Motorsports',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteUrl,
    siteName: 'SuperNatural Motorsports',
    title: 'SuperNatural Motorsports | Unleash Your Racing Spirit',
    description: 'Find your perfect sports car, plan performance builds with purpose, and join a community that values mastery over materialism. Excellence over ego—we lift up every driver.',
    // OG image is automatically generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SuperNatural Motorsports | Unleash Your Racing Spirit',
    description: 'Find your perfect sports car, plan builds with purpose, and join a community that values mastery over materialism. Excellence over ego.',
    // Twitter image is automatically generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: siteUrl,
  },
  category: 'automotive',
};

// JSON-LD Structured Data for Organization
const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'SuperNatural Motorsports',
  url: siteUrl,
  logo: `${siteUrl}/apple-icon`,
  description: 'Unleash your racing spirit. Sports car selection, performance builds, and a community built on excellence over ego. From Miatas to GT3s—we lift up every driver.',
  sameAs: [
    'https://instagram.com/supernaturalmotorsports',
    'https://youtube.com/@supernaturalmotorsports'
  ],
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer service',
    email: 'contact@supernaturalmotorsports.com',
  },
};

// JSON-LD for Website with SearchAction
const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'SuperNatural Motorsports',
  url: siteUrl,
  description: 'Unleash your racing spirit. Find your perfect sports car, plan performance builds with purpose, and join a community that values mastery over materialism.',
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${siteUrl}/car-selector?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta name="theme-color" content="#1a4d6e" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        {/* Favicon and Apple Touch Icon are auto-generated by app/icon.tsx and app/apple-icon.tsx */}
        <link rel="manifest" href="/manifest.json" />
        {/* JSON-LD Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body>
        <AuthProvider>
        <CarSelectionProvider>
        <FavoritesProvider>
        <CompareProvider>
        <SavedBuildsProvider>
          {/* Scroll to top on route change */}
          <Suspense fallback={null}>
            <ScrollToTop />
          </Suspense>
          <Header />
          {/* Selected Car Banner - shows when a car is selected */}
          <Suspense fallback={null}>
            <SelectedCarBanner />
          </Suspense>
          <main style={{ 
            flex: 1, 
            paddingTop: 'var(--header-height-mobile)',
            minHeight: 'calc(100dvh - var(--header-height-mobile))',
          }}>
            {children}
          </main>
          <Footer />
          {/* Selected Car Floating Widget */}
          <Suspense fallback={null}>
            <SelectedCarFloatingWidget />
          </Suspense>
          
          {/* Mobile sticky CTA bar - shows on scroll */}
          <MobileBottomCta />
        </SavedBuildsProvider>
        </CompareProvider>
        </FavoritesProvider>
        </CarSelectionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

